export const TOP_100_FILMS = [
  { title: "The Shawshank Redemption", label: 1994 },
  { title: "The Godfather", label: 1972 },
  { title: "The Godfather: Part II", label: 1974 },
  { title: "The Dark Knight", label: 2008 },
  { title: "12 Angry Men", label: 1957 },
  { title: "Schindler's List", label: 1993 },
  { title: "Pulp Fiction", label: 1994 },
  { title: "The Lord of the Rings: The Return of the King", label: 2003 },
  { title: "The Good, the Bad and the Ugly", label: 1966 },
  { title: "Fight Club", label: 1999 },
  { title: "The Lord of the Rings: The Fellowship of the Ring", label: 2001 },
  { title: "Star Wars: Episode V - The Empire Strikes Back", label: 1980 },
  { title: "Forrest Gump", label: 1994 },
  { title: "Inception", label: 2010 },
  { title: "The Lord of the Rings: The Two Towers", label: 2002 },
  { title: "One Flew Over the Cuckoo's Nest", label: 1975 },
  { title: "Goodfellas", label: 1990 },
  { title: "The Matrix", label: 1999 },
  { title: "Seven Samurai", label: 1954 },
  { title: "Star Wars: Episode IV - A New Hope", label: 1977 },
  { title: "City of God", label: 2002 },
  { title: "Se7en", label: 1995 },
  { title: "The Silence of the Lambs", label: 1991 },
  { title: "It's a Wonderful Life", label: 1946 },
  { title: "Life Is Beautiful", label: 1997 },
  { title: "The Usual Suspects", label: 1995 },
  { title: "Léon: The Professional", label: 1994 },
  { title: "Spirited Away", label: 2001 },
  { title: "Saving Private Ryan", label: 1998 },
  { title: "Once Upon a Time in the West", label: 1968 },
  { title: "American History X", label: 1998 },
  { title: "Interstellar", label: 2014 },
  { title: "Casablanca", label: 1942 },
  { title: "City Lights", label: 1931 },
  { title: "Psycho", label: 1960 },
  { title: "The Green Mile", label: 1999 },
  { title: "The Intouchables", label: 2011 },
  { title: "Modern Times", label: 1936 },
  { title: "Raiders of the Lost Ark", label: 1981 },
  { title: "Rear Window", label: 1954 },
  { title: "The Pianist", label: 2002 },
  { title: "The Departed", label: 2006 },
  { title: "Terminator 2: Judgment Day", label: 1991 },
  { title: "Back to the Future", label: 1985 },
  { title: "Whiplash", label: 2014 },
  { title: "Gladiator", label: 2000 },
  { title: "Memento", label: 2000 },
  { title: "The Prestige", label: 2006 },
  { title: "The Lion King", label: 1994 },
  { title: "Apocalypse Now", label: 1979 },
  { title: "Alien", label: 1979 },
  { title: "Sunset Boulevard", label: 1950 },
  {
    title:
      "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    label: 1964
  },
  { title: "The Great Dictator", label: 1940 },
  { title: "Cinema Paradiso", label: 1988 },
  { title: "The Lives of Others", label: 2006 },
  { title: "Grave of the Fireflies", label: 1988 },
  { title: "Paths of Glory", label: 1957 },
  { title: "Django Unchained", label: 2012 },
  { title: "The Shining", label: 1980 },
  { title: "WALL·E", label: 2008 },
  { title: "American Beauty", label: 1999 },
  { title: "The Dark Knight Rises", label: 2012 },
  { title: "Princess Mononoke", label: 1997 },
  { title: "Aliens", label: 1986 },
  { title: "Oldboy", label: 2003 },
  { title: "Once Upon a Time in America", label: 1984 },
  { title: "Witness for the Prosecution", label: 1957 },
  { title: "Das Boot", label: 1981 },
  { title: "Citizen Kane", label: 1941 },
  { title: "North by Northwest", label: 1959 },
  { title: "Vertigo", label: 1958 },
  { title: "Star Wars: Episode VI - Return of the Jedi", label: 1983 },
  { title: "Reservoir Dogs", label: 1992 },
  { title: "Braveheart", label: 1995 },
  { title: "M", label: 1931 },
  { title: "Requiem for a Dream", label: 2000 },
  { title: "Amélie", label: 2001 },
  { title: "A Clockwork Orange", label: 1971 },
  { title: "Like Stars on Earth", label: 2007 },
  { title: "Taxi Driver", label: 1976 },
  { title: "Lawrence of Arabia", label: 1962 },
  { title: "Double Indemnity", label: 1944 },
  { title: "Eternal Sunshine of the Spotless Mind", label: 2004 },
  { title: "Amadeus", label: 1984 },
  { title: "To Kill a Mockingbird", label: 1962 },
  { title: "Toy Story 3", label: 2010 },
  { title: "Logan", label: 2017 },
  { title: "Full Metal Jacket", label: 1987 },
  { title: "Dangal", label: 2016 },
  { title: "The Sting", label: 1973 },
  { title: "2001: A Space Odyssey", label: 1968 },
  { title: "Singin' in the Rain", label: 1952 },
  { title: "Toy Story", label: 1995 },
  { title: "Bicycle Thieves", label: 1948 },
  { title: "The Kid", label: 1921 },
  { title: "Inglourious Basterds", label: 2009 },
  { title: "Snatch", label: 2000 },
  { title: "3 Idiots", label: 2009 },
  { title: "Monty Python and the Holy Grail", label: 1975 }
].map((m, index) => ({ ...m, id: index + 1 }));
